name: Check for drift
on:
  - workflow_dispatch:
  - schedule:
      - cron: "0,15,30,45 * * * *"

jobs:
  check-for-drift:
    name: Run import and check for differences
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Refresh the import
        run: |
          make clean
          make
      - name: Fail if there are any changes from what's in git
        run: |
          [[ -z $(git status -s) ]]
