name: Check for drift
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  check-for-drift:
    name: Run import and check for differences
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Refresh the import
        run: |
          make clean
          make
      - name: Fail if there are any changes from what's in git
        run: |
          [[ -z $(git status -s) ]]
